# Generated by Django 5.2.4 on 2025-10-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('terminal', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='TerminalQueue',
        ),
    ]
