# Generated by Django 5.2.4 on 2025-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_systemsettings_entry_cooldown_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='departure_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Default duration (in minutes) before a vehicle departs automatically.'),
        ),
    ]
