# Generated by Django 5.2.4 on 2025-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0009_systemsettings_departure_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='bus_max_seats',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='jeepney_max_seats',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='van_max_seats',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='departure_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
