# Generated by Django 5.2.4 on 2025-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_qr_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='successful', max_length=15),
        ),
    ]
