# Generated by Django 5.2.7 on 2025-11-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_deposit_payment_method_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
