# Generated by Django 5.2.4 on 2026-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_rename_status_temp_vehicle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['origin', 'destination']},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_image',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(default=None, upload_to='driver_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(choices=[('professional', 'Professional Driver’s License')], default='professional', max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(help_text='Example: City A - City B', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cr_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Registration Certificate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='or_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Official Receipt Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(max_length=17, unique=True, verbose_name='Vehicle Identification Number (VIN)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_model',
            field=models.PositiveIntegerField(),
        ),
    ]
